### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by theRealBitcoinClub** [paytaca/paytaca-app#73]
I can offer you free german translation as I am a native speaker

**Comment by joemarct** [comment]
We are currently setting up multi-language support. When it's done, we will need translations in major languages, including German. We will update this issue when we are ready.

**Comment by joemarct** [comment]
@theRealBitcoinClub The German translations are here: https://github.com/paytaca/paytaca-app/blob/master/src/i18n/de/index.js

These are automatically generated using Google Translate. Let us know if there is anything that needs to be corrected or improved.
